### ISSUE TITLE
Problem: Nature can be a study program for beginner？

### ISSUE THREAD

**Issue by csh0101** [nature-lang/nature#15]
noob background:
-  see some scip
-  have base knowledge of compile Principles

**Comment by weiwenhao** [comment]
You are referring to a study plan for compiler principles. I have provided my [relevant learning roadmap (click here to jump to it)](https://nature-lang.org/docs/prologue/contribution-guide#%E7%9B%B8%E5%85%B3%E8%B5%84%E6%96%99) and you can choose to study the aspects that interest you. They are all good materials. In addition, the source code of Nature is very simple and contains many Chinese comments. If you need to practice and encounter difficulties, you can refer to the source code of Nature or communicate with me.

Another thing to consider is to clarify your learning goals. If you hope to find a related job, you can refer to the job requirements on recruitment websites and then conduct specialized learning, such as the common requirement of using and extending LLVM. The most important thing is to practice and further delve into the principles and essence in your work.

If you are studying compiler theory solely for personal interest, you can refer to the roadmap above for learning. For knowledge acquisition, I recommend documents, books, videos, etc. instead. Reading source code may not be particularly suitable for learning. Of course, even if it is for interest, applying what you learn is equally important.

**Comment by csh0101** [comment]
just for interest. Thanks
