### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by fenginsc** [nature-lang/nature#21]
1. don't use emoji in your code, you can't type this kind of thing directly on your keyboard, you have to resort to third party software, which is inefficient and doesn't make coding enjoyable. 
2. hopefully it will support windows.
Thanks!

**Comment by weiwenhao** [comment]
I have to agree with your suggestion. I will explore a better way to implement language features using macros, rather than directly using emojis.

**Comment by fenginsc** [comment]
@weiwenhao 
Thank you!
