### ISSUE TITLE
国人过来支持一下

### ISSUE THREAD

**Issue by cocowise** [nature-lang/nature#31]
本人文科生，只能反馈个typo：
https://nature-lang.org/zh-Hans/
主页最下方的“Discard“应为"Discord"

一门新的编程语言要成功殊为不易，需要一个社区的多年、共同努力，是N个马拉松的长跑，希望张弛有度、久久为功。

回顾那些成功的编程语言，都是借助那一波发展浪潮顺势发展起来的，往往是填补了当时其他语言的空白或与浪潮不相容的地方。
C -- 依托小型机微机上UNIX系统的流行而发展，C语言本身的设计从今天来看可商榷地方很多，但是当时是系统开发不二选的语言，累积至今的护城河更是难以逾越替代；
C++ -- 硬件软件的发展，使得软件的规模越来越大，面向对象的代码复用是软件工程化的必然要求，而且计算机的普及要求降低硬件成本，这个时候既实现面向对象、又能榨取硬件性能的C++腾空出世，到了现在虽然疆域有所缩小，语言本身变得越发臃肿，但仍处于壮年期。
Java/Javascript -- 这两种完全不同的编程语言，但其实正如名字所表明的、其起源上是有些许联系的，在发展中又都是互联网浪潮下编程语言的胜出者。Java在 server 后端，繁琐的语法看似自废武功，但正是如此才有利于水平各异、进进出出的程序员们各司其职、模块化协作构建出大型软件；Javascript在 client 前端，弱类型语法灵活，但某种程度上对于前端用户交互来说，高容错对计算机小白更为友好，毕竟小毛病问题不大不影响主要功能（开发者也省事了）。
Python -- 靠着语法简单友好和Cython成为Script胶水语言，在数值计算、人工智能这些当年还比较小众的niche领域猥琐发育了十多年。近几年，一个是人工智能的巨大浪潮，另一个是各行各业甚至文科专业越来越多的使用编程，Python 就是想不火都难……Excel都用Python了。
如今学编程、会编程的人越来越多，那么高手们怎么办？于是Rust的机会来了:-)但路还很长，还有不确定性……

希望Nature不断摸索自身的定位，笑到最后~

**Comment by weiwenhao** [comment]
感谢 🙏， 当我读 《球状闪电》 时我就觉得坚持做一件事情是非常酷的事情。所以我的信仰是 "择一事，终一生"。 

> 但也必须承认，这一年的世界变化让我变得太过急躁的想要推动 nature 的发展。

> 我待会把 discord 的链接下掉，还想着 discard 这名字这么奇怪。
