### ISSUE TITLE
Is there a version for Windows or a compilation from Linux?

### ISSUE THREAD

**Issue by Spoiledpay** [nature-lang/nature#38]
Hi, do we have a compiler for Windows? Would it be possible to have? And if not, what about the cross compiler issue. In Linux, create the program and ask it to be compiled into the executable for Windows?

BUILD_OS=windows BUILD_ARCH=amd64 nature build main.n

**Comment by weiwenhao** [comment]
Not yet, but there are plans to support the Windows/amd64 compiler
