### ISSUE TITLE
Add type alias?

### ISSUE THREAD

**Issue by Chanyon** [nature-lang/nature#6]
```c
type Fn = fn(uint) : uint
fn foo(): Fn {
  return fn(uint bar): uint {
    return bar
  }
}
```

**Comment by weiwenhao** [comment]
https://nature-lang.org/docs/the-basics/struct

It supports the type alias syntax. Here is an example of its usage, which is similar to the usage in your example. However, it seems that the documentation does not specifically mention this syntax, so I will update the documentation.

**Comment by Chanyon** [comment]
> https://nature-lang.org/docs/the-basics/struct
> 
> It supports the type alias syntax. Here is an example of its usage, which is similar to the usage in your example. However, it seems that the documentation does not specifically mention this syntax, so I will update the documentation.

I know it now.
